# 'cargo install toml-cli' <-- for scripting support
# Example call:
# ------
# [Main]
# test = "Hello World!"
# -----
# $: toml get config.toml Main.test --raw
# ~~ Hello World!
[wallpaper]
name = "blackwater.png"
path = "/usr/share/wallpaper"
